# config.toml
[master]
log_path = "logs"          # log storage

[chunkserver]
data_path = "data"      # Path to chunk data storage
log_path = "logs"       # Path to log storage

[client]
log_path = "client/logs" # Path to client log storage

[common]
master_addrs = ["127.0.0.1:50001", "127.0.0.1:50002", "127.0.0.1:50003"] # Using 2 shadow masters by default
heartbeat_interval = 20                  # Heartbeat interval from ChunkServer (in seconds)
chunk_size = 4096                        # Chunk size (in bytes)
max_allowed_chunks = 100                 # Maximum number of chunks each chunkserver can store
replication_factor = 3                   # Number of chunk replicas
log_level = "info"                       # Options are "debug", "info", "warn", "error"
log_output = "stdout"                    # Options are "stdout", "file"
